In [1]:
import pandas as pd

In [2]:
churn_analysis = pd.read_csv(r"C:\Users\amanb\Downloads\Telecom+Customer+Churn\telecom_customer_churn.csv")

In [3]:
churn_analysis.head()

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [4]:
churn_analysis.isnull().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Married                                 0
Number of Dependents                    0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges     682
Multiple Lines                        682
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download              1526
Online Security                      1526
Online Backup                        1526
Device Protection Plan               1526
Premium Tech Support                 1526
Streaming TV                         1526
Streaming Movies                     1526
Streaming Music                      1526
Unlimited Data                       1526
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Customer Status                         0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [5]:
churn_analysis["Offer"]= churn_analysis["Offer"].fillna(0)

In [29]:
churn_analysis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 40 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   customer_id                        7043 non-null   object
 1   gender                             7043 non-null   object
 2   age                                7043 non-null   int64
 3   married                            7043 non-null   object
 4   number_of_dependents               7043 non-null   int64
 5   city                               7043 non-null   object
 6   zip_code                           7043 non-null   int64
 7   latitude                           7043 non-null   float64
 8   longitude                          7043 non-null   float64
 9   number_of_referrals                7043 non-null   int64
 10  tenure_in_months                   7043 non-null   int64
 11  offer                              7043 non-null   object
 12  phone_service                      7043 non-null   object
 13  avg_monthly_long_distance_charges  7043 non-null   float64
 14  multiple_lines                     7043 non-null   object
 15  internet_service                   7043 non-null   object
 16  internet_type                      7043 non-null   object
 17  avg_monthly_gb_download            7043 non-null   float64
 18  online_security                    7043 non-null   object
 19  online_backup                      7043 non-null   object
 20  device_protection_plan             7043 non-null   object
 21  premium_tech_support               7043 non-null   object
 22  streaming_tv                       7043 non-null   object
 23  streaming_movies                   7043 non-null   object
 24  streaming_music                    7043 non-null   object
 25  unlimited_data                     7043 non-null   object
 26  contract                           7043 non-null   object
 27  paperless_billing                  7043 non-null   object
 28  payment_method                     7043 non-null   object
 29  monthly_charge                     7043 non-null   float64
 30  total_charges                      7043 non-null   float64
 31  total_refunds                      7043 non-null   float64
 32  total_extra_data_charges           7043 non-null   int64
 33  total_long_distance_charges        7043 non-null   float64
 34  total_revenue                      7043 non-null   float64
 35  customer_status                    7043 non-null   object
 36  churn_category                     7043 non-null   object
 37  churn_reason                       7043 non-null   object
 38  multiple_lines__                   7043 non-null   object
 39  online_security_                   7043 non-null   object
dtypes: float64(9), int64(6), object(25)
memory usage: 2.1+ MB

In [31]:
churn_analysis.describe()

,age,number_of_dependents,zip_code,latitude,longitude,number_of_referrals,tenure_in_months,avg_monthly_long_distance_charges,avg_monthly_gb_download,monthly_charge,total_charges,total_refunds,total_extra_data_charges,total_long_distance_charges,total_revenue
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,0.468692,93486.070567,36.197455,-119.756684,1.951867,32.386767,22.958954,20.515405,63.596131,2280.381264,1.962182,6.860713,749.099262,3034.379056
std,16.750352,0.962802,1856.767505,2.468929,2.154425,3.001199,24.542061,15.448113,20.418940,31.204743,2266.220462,7.902614,25.104978,846.660055,2865.204542
min,19.000000,0.000000,90001.000000,32.555828,-124.301372,0.000000,1.000000,0.000000,0.000000,-10.000000,18.800000,0.000000,0.000000,0.000000,21.360000
25%,32.000000,0.000000,92101.000000,33.990646,-121.788090,0.000000,9.000000,9.210000,3.000000,30.400000,400.150000,0.000000,0.000000,70.545000,605.610000
50%,46.000000,0.000000,93518.000000,36.205465,-119.595293,0.000000,29.000000,22.890000,17.000000,70.050000,1394.550000,0.000000,0.000000,401.440000,2108.640000
75%,60.000000,0.000000,95329.000000,38.161321,-117.969795,3.000000,55.000000,36.395000,27.000000,89.750000,3786.600000,0.000000,0.000000,1191.100000,4801.145000
max,80.000000,9.000000,96150.000000,41.962127,-114.192901,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000

In [32]:
churn_analysis.shape

(7043, 40)

In [6]:
churn_analysis.isnull().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Married                                 0
Number of Dependents                    0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Number of Referrals                     0
Tenure in Months                        0
Offer                                   0
Phone Service                           0
Avg Monthly Long Distance Charges     682
Multiple Lines                        682
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download              1526
Online Security                      1526
Online Backup                        1526
Device Protection Plan               1526
Premium Tech Support                 1526
Streaming TV                         1526
Streaming Movies                     1526
Streaming Music                      1526
Unlimited Data                       1526
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Customer Status                         0
Churn Category                       5174
Churn Reason                         5174
dtype: int64

In [7]:
churn_analysis["Avg Monthly Long Distance Charges"]= churn_analysis["Avg Monthly Long Distance Charges"].fillna(0)

In [8]:
churn_analysis["Multiple Lines  "]= churn_analysis["Multiple Lines"].fillna(0)

In [9]:
churn_analysis["Internet Type"]= churn_analysis["Internet Type"].fillna(0)

In [10]:
churn_analysis["Avg Monthly GB Download"]= churn_analysis["Avg Monthly GB Download"].fillna(0)

In [11]:
churn_analysis["Online Security "]= churn_analysis["Online Security"].fillna(0)

In [12]:
churn_analysis["Online Backup"]= churn_analysis["Online Backup"].fillna(0)

In [13]:
churn_analysis["Device Protection Plan"]= churn_analysis["Device Protection Plan"].fillna(0)

In [14]:
churn_analysis["Premium Tech Support"]= churn_analysis["Premium Tech Support"].fillna(0)

In [15]:
churn_analysis["Streaming TV"]= churn_analysis["Streaming TV"].fillna(0)

In [16]:
churn_analysis["Streaming Movies"]= churn_analysis["Streaming Movies"].fillna(0)

In [17]:
churn_analysis["Streaming Music"]= churn_analysis["Streaming Music"].fillna(0)

In [18]:
churn_analysis["Unlimited Data"]= churn_analysis["Unlimited Data"].fillna(0)

In [19]:
churn_analysis["Churn Category"]= churn_analysis["Churn Category"].fillna(0)

In [20]:
churn_analysis["Churn Reason"]= churn_analysis["Churn Reason"].fillna(0)

In [21]:
churn_analysis.isnull().sum()

Customer ID                             0
Gender                                  0
Age                                     0
Married                                 0
Number of Dependents                    0
City                                    0
Zip Code                                0
Latitude                                0
Longitude                               0
Number of Referrals                     0
Tenure in Months                        0
Offer                                   0
Phone Service                           0
Avg Monthly Long Distance Charges       0
Multiple Lines                        682
Internet Service                        0
Internet Type                           0
Avg Monthly GB Download                 0
Online Security                      1526
Online Backup                           0
Device Protection Plan                  0
Premium Tech Support                    0
Streaming TV                            0
Streaming Movies                        0
Streaming Music                         0
Unlimited Data                          0
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Customer Status                         0
Churn Category                          0
Churn Reason                            0
Multiple Lines                          0
Online Security                         0
dtype: int64

In [22]:
churn_analysis["Multiple Lines"]= churn_analysis["Multiple Lines"].fillna(0)

In [23]:
churn_analysis["Online Security"]= churn_analysis["Online Security"].fillna(0)

In [24]:
churn_analysis.isnull().sum()

Customer ID                          0
Gender                               0
Age                                  0
Married                              0
Number of Dependents                 0
City                                 0
Zip Code                             0
Latitude                             0
Longitude                            0
Number of Referrals                  0
Tenure in Months                     0
Offer                                0
Phone Service                        0
Avg Monthly Long Distance Charges    0
Multiple Lines                       0
Internet Service                     0
Internet Type                        0
Avg Monthly GB Download              0
Online Security                      0
Online Backup                        0
Device Protection Plan               0
Premium Tech Support                 0
Streaming TV                         0
Streaming Movies                     0
Streaming Music                      0
Unlimited Data                       0
Contract                             0
Paperless Billing                    0
Payment Method                       0
Monthly Charge                       0
Total Charges                        0
Total Refunds                        0
Total Extra Data Charges             0
Total Long Distance Charges          0
Total Revenue                        0
Customer Status                      0
Churn Category                       0
Churn Reason                         0
Multiple Lines                       0
Online Security                      0
dtype: int64

In [25]:
churn_analysis.columns = churn_analysis.columns.str.replace(" ","_")
churn_analysis.columns = churn_analysis.columns.str.lower()

In [26]:
churn_analysis.columns

Index(['customer_id', 'gender', 'age', 'married', 'number_of_dependents',
       'city', 'zip_code', 'latitude', 'longitude', 'number_of_referrals',
       'tenure_in_months', 'offer', 'phone_service',
       'avg_monthly_long_distance_charges', 'multiple_lines',
       'internet_service', 'internet_type', 'avg_monthly_gb_download',
       'online_security', 'online_backup', 'device_protection_plan',
       'premium_tech_support', 'streaming_tv', 'streaming_movies',
       'streaming_music', 'unlimited_data', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charge', 'total_charges', 'total_refunds',
       'total_extra_data_charges', 'total_long_distance_charges',
       'total_revenue', 'customer_status', 'churn_category', 'churn_reason',
       'multiple_lines__', 'online_security_'],
      dtype='object')

In [27]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:aman123@localhost:3306/Churn_analysis")

churn_analysis.to_sql(
    name="telecom_data",
    con=engine,
    if_exists="replace",   
    index=False
)

7043

In [28]:
churn_analysis.to_csv("telecom_data.csv",
index = False, encoding = "utf-8-sig")